/**
 * Claude Code hook event plumbing.
 *
 * Claude runs a command hook for each lifecycle event and passes a JSON payload
 * on stdin. A tiny writer script is generated per child and appends those
 * payloads to an append-only `events.jsonl`, which is tailed here.
 *
 * A plain file rather than a FIFO: a FIFO write blocks until a reader attaches,
 * which would hang the child whenever the runner is not listening. A plain file
 * is also replayable by byte offset after a restart.
 */

import * as fs from "node:fs";
import * as path from "node:path";

/** Payload shapes this runner cares about. Claude sends more fields than these. */
export interface HookEvent {
	hook_event_name: string;
	session_id?: string;
	prompt_id?: string;
	transcript_path?: string;
	cwd?: string;
	/** Stop: the child's final message for the turn. This is the deliverable. */
	last_assistant_message?: string;
	/** Notification: e.g. "Claude needs your permission to use Bash". */
	message?: string;
	/** PreToolUse. */
	tool_name?: string;
	tool_input?: unknown;
	/** UserPromptSubmit. */
	prompt?: string;
	stop_hook_active?: boolean;
	reason?: string;
	/** Added by the writer script, ms since epoch. */
	__received: number;
}

export const HOOK_EVENTS = ["UserPromptSubmit", "Stop", "Notification", "PreToolUse", "SessionEnd"] as const;

export const EVENTS_FILE = "events.jsonl";
/**
 * `.cjs`, never `.js`: the state dir lives under the user's project, and a
 * project declaring `"type": "module"` would make a `.js` hook ESM, where
 * `require` is undefined and every hook invocation would fail silently.
 */
const HOOK_FILE = "hook.cjs";
const SETTINGS_FILE = "settings.json";

function shellQuote(value: string): string {
	return `'${value.replaceAll("'", `'\\''`)}'`;
}

export function eventsPathFor(stateDir: string): string {
	return path.join(stateDir, EVENTS_FILE);
}

/**
 * Write the hook writer script and the settings file Claude is launched with.
 * Returns the path to pass to `--settings`.
 */
export function writeHookConfig(stateDir: string, options: { nodePath: string; progress: boolean }): string {
	fs.mkdirSync(stateDir, { recursive: true });

	const eventsPath = eventsPathFor(stateDir);
	const hookPath = path.join(stateDir, HOOK_FILE);
	const settingsPath = path.join(stateDir, SETTINGS_FILE);

	if (!fs.existsSync(eventsPath)) fs.writeFileSync(eventsPath, "");

	fs.writeFileSync(
		hookPath,
		`// Generated by the pi-subagents tmux-pane runner. Appends hook payloads to events.jsonl.
const fs = require("node:fs");
const EVENTS = ${JSON.stringify(eventsPath)};
let buf = "";
process.stdin.setEncoding("utf8");
process.stdin.on("data", (d) => (buf += d));
process.stdin.on("end", () => {
	let payload;
	try {
		payload = JSON.parse(buf);
	} catch {
		payload = { hook_event_name: "ParseError", raw: buf.slice(0, 4000) };
	}
	payload.__received = Date.now();
	try {
		fs.appendFileSync(EVENTS, JSON.stringify(payload) + "\\n");
	} catch {}
	process.exit(0);
});
`,
	);

	const command = `${shellQuote(options.nodePath)} ${shellQuote(hookPath)}`;
	const entry = { hooks: [{ type: "command", command, timeout: 5 }] };

	const hooks: Record<string, unknown[]> = {};
	for (const name of HOOK_EVENTS) {
		if (name === "PreToolUse" && !options.progress) continue;
		hooks[name] = [entry];
	}

	fs.writeFileSync(settingsPath, JSON.stringify({ hooks }, null, 2));
	return settingsPath;
}

/** Append a synthetic event so runner-side actions appear in the same stream. */
export function appendLocalEvent(stateDir: string, event: Partial<HookEvent> & { hook_event_name: string }): void {
	try {
		fs.appendFileSync(eventsPathFor(stateDir), `${JSON.stringify({ ...event, __received: Date.now() })}\n`);
	} catch {
		// The event stream is diagnostic; losing a synthetic entry must not fail a turn.
	}
}

type Listener = (event: HookEvent) => void;

/**
 * Polls `events.jsonl` for appended lines and fans them out to listeners.
 *
 * Polling rather than fs.watch: watch semantics for appends differ across
 * platforms, and 200ms is far below the latency of an agent turn.
 */
export class EventTail {
	private readonly file: string;
	private offset = 0;
	private partial = "";
	private timer: ReturnType<typeof setInterval> | undefined;
	private readonly listeners = new Set<Listener>();
	private readonly recent: HookEvent[] = [];
	private readonly intervalMs: number;

	constructor(stateDir: string, intervalMs = 200) {
		this.file = eventsPathFor(stateDir);
		this.intervalMs = intervalMs;
	}

	/** Skip everything already in the file (used when adopting an existing pane). */
	seekToEnd(): void {
		try {
			this.offset = fs.statSync(this.file).size;
		} catch {
			this.offset = 0;
		}
	}

	start(): void {
		if (this.timer) return;
		this.timer = setInterval(() => this.poll(), this.intervalMs);
		// A poll timer must not keep the process alive on its own.
		this.timer.unref?.();
	}

	stop(): void {
		if (!this.timer) return;
		clearInterval(this.timer);
		this.timer = undefined;
	}

	subscribe(listener: Listener): () => void {
		this.listeners.add(listener);
		return () => this.listeners.delete(listener);
	}

	history(limit: number): HookEvent[] {
		return this.recent.slice(-limit);
	}

	/** Drain synchronously. Exposed so tests need not wait on the interval. */
	poll(): void {
		let size: number;
		try {
			size = fs.statSync(this.file).size;
		} catch {
			return;
		}

		// File replaced or truncated between polls.
		if (size < this.offset) {
			this.offset = 0;
			this.partial = "";
		}
		if (size === this.offset) return;

		let chunk = "";
		try {
			const fd = fs.openSync(this.file, "r");
			try {
				const buffer = Buffer.alloc(size - this.offset);
				const read = fs.readSync(fd, buffer, 0, buffer.length, this.offset);
				chunk = buffer.subarray(0, read).toString("utf-8");
				this.offset += read;
			} finally {
				fs.closeSync(fd);
			}
		} catch {
			return;
		}

		this.partial += chunk;
		const lines = this.partial.split("\n");
		this.partial = lines.pop() ?? "";

		for (const line of lines) {
			if (!line.trim()) continue;
			let event: HookEvent;
			try {
				event = JSON.parse(line) as HookEvent;
			} catch {
				continue;
			}
			this.recent.push(event);
			if (this.recent.length > 200) this.recent.shift();
			for (const listener of [...this.listeners]) {
				try {
					listener(event);
				} catch {
					// A misbehaving listener must not stall the tail.
				}
			}
		}
	}
}
